mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.yk.ihrm.mybatis.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 9090
  tomcat:
    uri-encoding: UTF-8
    connection-timeout: 20000
    keep-alive-timeout: 60000
    max-keep-alive-requests: 60000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ihrm
    username: root
    password: 123
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 1800000
